name = "atlanta-gutter-guard-pros"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

# Production environment configuration
[env.production]
account_id = "8e14a0cc7cbc906fd65a75e8f5218e35"

# Environment variables for production
[env.production.vars]
# MISTRAL_API_KEY will be set via wrangler secret

# Environment variables for local development
[vars]
# Add your Mistral API key here for local development only
# MISTRAL_API_KEY = "your-key-here"
